### ISSUE TITLE
Use of 'replace' in DDO

### ISSUE THREAD

**Issue by vmaimone** [orizens/angular-es2015-styleguide#1]
The replace option should not be recommended as per the angular documentation for [$compile](https://docs.angularjs.org/api/ng/service/$compile).  This option has been deprecated.

**Comment by orizens** [comment]
can you put out an example?

**Comment by zachlysobey** [comment]
`replace: true` is used in your example here:
https://github.com/orizens/angular-es2015-styleguide#module-namecomponentjs---component-defintion-with-controller-class

(on an unrelated note, that example has weird/inconsistent indentation)

**Comment by orizens** [comment]
@zachlysobey - thanks.
I'm about to update the indentation example.

**Comment by orizens** [comment]
@vmaimone 
the absence of `replace` is relevant when there's real web component support, as state in the same link you've provided: 

> replace ([DEPRECATED!], will be removed in next major release - i.e. v2.0)
